nelmio_api_doc:
    documentation:
        info:
            title: AaxisTest
            description: Documentation of API
            version: 1.0.0
        components:
            securitySchemes:
                X-AUTH-TOKEN:
                    type: apiKey
                    description: 'X-AUTH-TOKEN: {apiKey}'
                    name: X-AUTH-TOKEN
                    in: header

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - /createClient
