security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        secured_area:
            pattern: ^/api
            custom_authenticator: App\Security\TokenAuthenticator
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: api_login
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    access_control:
        - { path: ^/, roles: PUBLIC_ACCESS  }
        - { path : ^/api, roles: [IS_AUTHENTICATED_FULLY] }
        - { path : ^/createClient, roles: PUBLIC_ACCESS  }
